# development postgres database
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: spm
      POSTGRES_PASSWORD: spm
      POSTGRES_DB: spm
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
